workflows:
  android-build:
    name: Android build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Generate localization and adapters
        script: dart run build_runner build --delete-conflicting-outputs
      - name: Build release APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk

  ios-build:
    name: iOS build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Generate localization and adapters
        script: dart run build_runner build --delete-conflicting-outputs
      - name: Build iOS without code signing
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app